import type {
  Anforderung,
  Baustelle,
  Benutzer,
  Einsatz,
  Kolonne,
  Materialart,
} from "./types";
import { berechneKgProM2, berechneTonnage } from "./calc";

export const SEED_BENUTZER: Benutzer[] = [
  {
    id: "u1",
    name: "Heinrich Lang",
    email: "bauleiter@asphalt-takt.de",
    rolle: "bauleiter",
    firma: "Josef Hebel GmbH & Co. KG",
  },
  {
    id: "u2",
    name: "Sabine Disponent",
    email: "disposition@asphalt-takt.de",
    rolle: "disposition",
    firma: "Josef Hebel GmbH & Co. KG",
  },
  {
    id: "u3",
    name: "Admin Verwaltung",
    email: "admin@asphalt-takt.de",
    rolle: "admin",
    firma: "Josef Hebel GmbH & Co. KG",
  },
];

export const SEED_BAUSTELLEN: Baustelle[] = [
  {
    id: "b1",
    ordner_nr: "1/5/26",
    baustellennummer: "97200350",
    name: "MM Fernwärme Riedbachstraße",
    adresse: "Riedbachstraße 12, 87700 Memmingen",
    ansprechpartner: "Bijedic Kerim",
    hinweis: "Mischgut wird von A+B Ingoldingen frei Bau bezogen.",
    status: "aktiv",
  },
  {
    id: "b2",
    ordner_nr: "2/3/26",
    baustellennummer: "260010005",
    name: "Winterrieden, BG Bachhäcker - MOTZ",
    adresse: "87785 Babenhausen",
    ansprechpartner: "Esser",
    hinweis: "Neue Anforderung aus dem gemeinsamen Datenbestand.",
    status: "aktiv",
  },
  {
    id: "b3",
    ordner_nr: "3/1/26",
    baustellennummer: "260010099",
    name: "Parkplatz Dachser Memmingen",
    adresse: "Robert-Bosch-Straße 1, 87700 Memmingen",
    ansprechpartner: "Frey",
    hinweis: "Anlieferung nur vormittags möglich.",
    status: "aktiv",
  },
];

export const SEED_MATERIAL: Materialart[] = [
  {
    id: "m1",
    material_nr: "101",
    bezeichnung: "AC 32 TS 50/70",
    kategorie: "tragschicht",
    standard_lkw: 0,
    standard_taktung_min: 0,
  },
  {
    id: "m2",
    material_nr: "308",
    bezeichnung: "AC 22 BS 10/40-65",
    kategorie: "binderschicht",
    standard_lkw: 0,
    standard_taktung_min: 0,
  },
  {
    id: "m3",
    material_nr: "309",
    bezeichnung: "AC 16 BS SG 25/55-55",
    kategorie: "binderschicht",
    standard_lkw: 0,
    standard_taktung_min: 0,
  },
  {
    id: "m4",
    material_nr: "411",
    bezeichnung: "AC 11 DS 50/70",
    kategorie: "deckschicht",
    standard_lkw: 0,
    standard_taktung_min: 0,
  },
  {
    id: "m5",
    material_nr: "415",
    bezeichnung: "SMA 8 S 25/55-55",
    kategorie: "deckschicht",
    standard_lkw: 0,
    standard_taktung_min: 0,
  },
];

export const SEED_KOLONNEN: Kolonne[] = [
  { id: "k1", name: "Becirovic", farbe: "#E8E000", aktiv: true },
  { id: "k2", name: "Schmid", farbe: "#005A9A", aktiv: true },
  { id: "k3", name: "Müller", farbe: "#E8730C", aktiv: true },
];

function pos(
  id: string,
  material_id: string,
  flaechen_bezeichnung: string,
  flaeche_m2: number,
  schichtdicke_cm: number,
  einbautag?: string
) {
  const kg = berechneKgProM2(schichtdicke_cm);
  return {
    id,
    material_id,
    flaechen_bezeichnung,
    flaeche_m2,
    schichtdicke_cm,
    kg_pro_m2: kg,
    tonnage: berechneTonnage(flaeche_m2, kg),
    einbautag,
  };
}

export const SEED_ANFORDERUNGEN: Anforderung[] = [
  {
    id: "a1",
    baustelle_id: "b1",
    kostenstelle: "97200350",
    ansprechpartner: "Bijedic Kerim",
    adresse: "Riedbachstraße 12, 87700 Memmingen",
    breitengrad: 47.982043,
    laengengrad: 10.188571,
    wunschtermin: "2026-06-19",
    prioritaet: "hoch",
    zeitraum_von: "2026-07-02",
    zeitraum_bis: "2026-07-07",
    dauer_std: 36,
    status: "neu_erfasst",
    notiz: "Mischgut wird von A+B Ingoldingen frei Bau bezogen.",
    fahrbahnbreite_min: 6,
    fahrbahnbreite_max: 7.5,
    eingespannt: true,
    erfasst_von: "u1",
    erstellt_am: "2026-06-15T08:00:00.000Z",
    materialien: [pos("p1", "m1", "Fahrbahn", 3000, 18, "2026-07-02")],
  },
  {
    id: "a2",
    baustelle_id: "b2",
    kostenstelle: "260010005",
    ansprechpartner: "Esser",
    adresse: "87785 Babenhausen",
    breitengrad: 48.0,
    laengengrad: 10.25,
    wunschtermin: "2026-06-24",
    prioritaet: "mittel",
    dauer_std: 10,
    status: "in_pruefung",
    notiz: "Eingespannt, Schächte vorhanden.",
    schaechte_anzahl: 3,
    eingespannt: true,
    erfasst_von: "u1",
    erstellt_am: "2026-06-16T09:30:00.000Z",
    materialien: [
      pos("p2", "m2", "Fahrbahn", 1200, 8, "2026-06-24"),
      pos("p3", "m4", "Deckschicht", 1200, 4, "2026-06-25"),
    ],
  },
  {
    id: "a3",
    baustelle_id: "b3",
    kostenstelle: "260010099",
    ansprechpartner: "Frey",
    adresse: "Robert-Bosch-Straße 1, 87700 Memmingen",
    breitengrad: 47.9889,
    laengengrad: 10.1525,
    wunschtermin: "2026-06-15",
    prioritaet: "hoch",
    zeitraum_von: "2026-06-15",
    zeitraum_bis: "2026-06-16",
    dauer_std: 20,
    status: "planung_vervollstaendigt",
    notiz: "Parkplatzfläche, Anlieferung nur vormittags.",
    erfasst_von: "u1",
    erstellt_am: "2026-06-10T07:15:00.000Z",
    materialien: [pos("p4", "m5", "Parkplatz", 2500, 4, "2026-06-15")],
  },
  {
    id: "a4",
    baustelle_id: "b1",
    kostenstelle: "97200350",
    ansprechpartner: "Bijedic Kerim",
    adresse: "Riedbachstraße 12, 87700 Memmingen",
    breitengrad: 47.982043,
    laengengrad: 10.188571,
    wunschtermin: "2026-06-12",
    prioritaet: "niedrig",
    dauer_std: 8,
    status: "abgeschlossen",
    notiz: "Anschluss Gehweg.",
    erfasst_von: "u1",
    erstellt_am: "2026-06-05T06:00:00.000Z",
    materialien: [pos("p5", "m4", "Gehweg", 600, 3, "2026-06-12")],
  },
];

export const SEED_EINSAETZE: Einsatz[] = [
  {
    id: "e1",
    kolonne_id: "k1",
    anforderung_id: "a3",
    datum: "2026-06-15",
    startzeit: "06:00",
    dauer_std: 10,
    status: "planung_vervollstaendigt",
  },
  {
    id: "e2",
    kolonne_id: "k2",
    anforderung_id: "a3",
    datum: "2026-06-16",
    startzeit: "06:00",
    dauer_std: 10,
    status: "planung_vervollstaendigt",
  },
  {
    id: "e3",
    kolonne_id: "k3",
    anforderung_id: "a2",
    datum: "2026-06-24",
    startzeit: "07:00",
    dauer_std: 10,
    status: "in_pruefung",
  },
];
